---
title: "Introduction to R: practical 2.1"
author: "PBRC: DA Hughes"
date: "Oct 16th, 2024"
output: html_document
---

### Your first R script

In this practical you will be writing your first R Script. 


I would like for you to:

  1. create a new project directory on your computer within a parental directory for this course. 
    
      
      For example I might have a directory like: "/Users/me/documents/work/synergy/education/intro_to_r/"
      
      I may create within this directory a new folder structure that looks like:
      
        - practical_2_1
          - data
          - results
          - scripts
<br>          
  2. Copy the data set [practical_2_1_data.txt]() to your data directory.
  3. Start and save a new R Script in your scripts directory.
  4. Then answer the following questions will maintaining **GOOD** script.
  
### Information about the data set.

  1. I simulated this data set using the script "03a_data_simulation.rmd"
  2. It includes the variables sex, height, weight and a number of features "f##" that you can think of as molecular traits. 
  3. The data was simulated such that there is correlation structure among the variables. 

### To record your answers you can add them as comments in your R script

      ## Answer: TRUE

### Questions and Tasks

  1. Is the data you read in a data frame?
  2. How many individuals are in the data set?
  3. How many rows are in the data set?
  4. How many features ("f__") are in the data set?
  5. Estimate the number of missing values for each variable?
  6. What is the Pearson's r (correlation) between height and weight?
  7. How much of the variance in weight is explained by height?
      - hint: You have Pearson's r. What is r^2?
  8. Sex is numeric (females = 0, males = 1) in your data frame. Make it a factor.
  9. Is there a sex  effect on height?
  10. Make a box plot of the effect of sex on height.
  11. Write this box plot as a pdf to your results directory.
  12. Estimate a correlation matrix of all the features among themselves (m-x-m matrix). 
  13. Write this matrix to your results directory.
  14. Estimate BMI and add it to the data set.
  15. What is the mean BMI in the data set?
  16. What is the mean BMI for males (1) and females (0)
  17. What is the range (min, max) observed?
  18. What is the 95% CI of the BMI distribtion?
  19. Is there an association between BMI and the first feature (f1)?
  20. Fit a multivariable model defining f1 as the dependent (outcome) variable and sex, age, and BMI as the independent variables.
  21. Is there an association between sex, age, and BMI, on f1?
  22. Can you write a loop, (s)apply function, or your own function to return a table of the beta, se, and p values for sex, age, and BMI on each feature in the data set? Include the sample size of each analysis as well. 
  23. How many of the features have a BMI effect / association?
  24. Which features have an assocation with BMI?
  25. Write this table to your results directory.
  
  
## Congratulations !!        

### You are done.



